### ISSUE TITLE
api key issue

### ISSUE THREAD

**Issue by jakeres** [wakatime/eclipse-wakatime#3]
hi
i have an issue with step 3. (eclipse luna/windows 7 - 64bit)
3.You will see a prompt asking for your api key. Enter your api key, then click OK.

i can`t store anywhere the api. do you know how to add it manually?
thanks.

**Comment by alanhamlett** [comment]
Hi @jakeres,

You can manually edit your api key from inside Eclipse with: `File -> WakaTime -> API Key`

**Comment by LeoDutra** [comment]
Now, after fixing issue https://github.com/wakatime/eclipse-wakatime/issues/6 ("Eclipse Update Site not working"), Wakatime does install but never asks for API key on Eclipse and no data linked to Eclipse is shown by the debug log (only Sublime heartbeat).

My Eclipse 3.6 with IBM RAD 8.5 does not show `File -> WakaTime` (tried the main perspectives).

**Comment by LeoDutra** [comment]
Added `api_key` to `.wakatime.cfg` but seems that plugin is "dead" inside Eclipse. No error log, no heartbeat, not in `Window -> General -> Startup and Shutdown`.

**Comment by alanhamlett** [comment]
Yes, if there is no `File -> WakaTime -> API Key` menu then the plugin was not loaded into Eclipse. Where can I download IBM Rational Developer to test it on my end?

**Comment by alanhamlett** [comment]
You can also check that WakaTime is installed from the Available Update Sites preference section:

![screen shot 2015-06-30 at 7 30 06 pm](https://cloud.githubusercontent.com/assets/522344/8446397/8fa2a82a-1f5e-11e5-8e35-77dea6692dbf.png)

**Comment by LeoDutra** [comment]
Made it. Reinstalled RAD and tried "defensive patterns". 

Platform: Ubuntu/Linux 14.04 LTS

Reinstalled RAD, removing any lasting folder, because I broke Equinox P2 update mechanism trying to fix it all manually.

After install:

1. started RAD using `sudo`;
2. changed Eclipse network mode to `direct`;
3. tried to install Wakatime from `Help -> Install New Software`;
4. got "Missing: Apache HttpComponents HttpClient OSGi bundle 4.1.3.v201209201135 eclipse" on `Window -> Show View -> Error Log`;
5. Downloaded  [Apache HttpComponents HttpClient OSGi bundle 4.1.3](http://archive.apache.org/dist/httpcomponents/httpcore/binary/) from Apache Httpcomponents archive;
6. extract and move `org.apache.httpcomponents.httpclient_4.1.3.jar` to `/opt/IBM/SDP85/p2/cic.p2.cache.location/plugins`;
7. restart RAD as `sudo`;
8. install Wakatime;
9. restart and enter API key.



How to install IBM Rational Application Developer:

1. Create IBM ID;
2. Install [IBM Installation Manager](http://www-01.ibm.com/support/docview.wss?uid=swg27025142);
3. Log into [IBM Passport Advantage](http://www-01.ibm.com/software/passportadvantage/pao_customer.html);
4. Download [IBM Rational Application Developer] for IBM Installation Manager (http://www-01.ibm.com/support/knowledgecenter/SSRTLW_8.5.5/com.ibm.rad.install.doc/topics/c_im_gui_scenarios.html?lang=en);
5. After install, reopen Installation Manager and update RAD to 8.5.5.2 (the latest right now).

**Comment by willowcheng** [comment]
Can we add `File -> WakaTime -> API Key` as alternative way for step 3?
> 3. Enter your api key, then click OK.

As tried both Eclipse Mars and Neon, I didn't get any prompt after installing the plugin. Thinking it would be very useful if someone gets into similar trouble.

**Comment by leodutra** [comment]
@willowcheng 

> As tried both Eclipse Mars and Neon, I didn't get any prompt after installing the plugin. 

Happens when plugin is incompatible or an error occurs. Check Eclipse error log.

**Comment by LohitakshTrehan** [comment]
Not asking for API on Webstorm also, everything is updated, also unistalled and installed again, but not helping

**Comment by alanhamlett** [comment]
These instructions should help:

[How to debug WakaTime plugins](https://wakatime.com/faq#debug-plugins)
