### ISSUE TITLE
Eclipse Update Site not working

### ISSUE THREAD

**Issue by rknall** [wakatime/eclipse-wakatime#6]
I am trying to install WakaTime on Eclipse. Using the given URL https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/ I only get a 400:Bad Request error.

Has the URL changed?

**Comment by LeoDutra** [comment]
Weird part: Eclipse still finds it.

**Comment by alanhamlett** [comment]
@rknall that's a problem with older versions of Eclipse which don't support the latest update site spec.

**Comment by LeoDutra** [comment]
There's many people working here with IBM RAD 8.5. It wraps an Eclipse 3.6.
Any ideas on how to fix it?

**Comment by alanhamlett** [comment]
I just tested with Eclipse v3.6.2 and the update site link above works fine.

**Comment by LeoDutra** [comment]
@alanhamlett, @rknall probably tried to install from the update site. 

My 3.6 finds and downloads Wakatime, but fails on local install because of missing Apache HttpClient and HttpCore.

![screenshot from 2015-06-24 11 52 34](https://cloud.githubusercontent.com/assets/444344/8333061/91153f16-1a67-11e5-99fd-92a93cfb1393.png)


Accessing the update site URL with a browser shows the 404 error. It happens for me too.

![screenshot from 2015-06-24 11 53 25](https://cloud.githubusercontent.com/assets/444344/8333077/a46711ca-1a67-11e5-80b9-7c8e75cbf244.png)


eclipse.buildId=unknown
java.fullversion=JRE 1.7.0 IBM J9 2.6 Linux amd64-64 Compressed References 20120809_118929 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR2_20120809_0948_B118929
JIT  - r11.b01_20120808_24925
GC   - R26_Java726_SR2_20120809_0948_B118929_CMPRSS
J9CL - 20120809_118929
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.ibm.rational.rad.product.v85.ide
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product com.ibm.rational.rad.product.v85.ide

**Comment by rknall** [comment]
The URL still leads to a 400 Site error for me. I have now installed Mars, which was released in June, and after adding the Site, during the initial request, the installer tells me the following:

Unable to read repository at https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/content.xml.
Unable to read repository at https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Weird thing, on my PC at home it was working fine, but not for the last 2-3 days

**Comment by LeoDutra** [comment]
I've had some problems with GitHub headers in the past. Maybe this raw is not intended do be linked for production purpouses?

**Comment by LeoDutra** [comment]
`content.xml` 404 for me too.

**Comment by alanhamlett** [comment]
Yes, this is normal and part of Eclipse update site protocol. Eclipse looks for a `site.xml` file at that url, which exists:

https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/site.xml

That's why the plugin installs in eclipse even though the url `https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/` returns a 404.

**Comment by alanhamlett** [comment]
@rknall maybe github was having an issue when returning a 400... it returns a 404 for me.

**Comment by LeoDutra** [comment]
Problem solved updating IBM Rational Developer to 8.5.5.2. 
That's why I "love" IBM.
